version: "3.9"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      VPN_SERVICE_PROVIDER: ${VPN_PROVIDER_STRING}
      OPENVPN_USER: ${VPN_USERNAME}
      OPENVPN_PASSWORD: ${VPN_PASSWORD}
      SERVER_REGIONS: ${VPN_REGION_STRING}
    ports:
      - 3000:3000/tcp
      - 3001:3001/tcp
    volumes:
      - ${PIMILOR_GLUETUN_PATH}:/gluetun
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: pimilor-firefox
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    # ports:
    # - 3000:3000
    # - 3001:3001
    network_mode: "service:gluetun"
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    shm_size: "1gb"
    volumes:
      - ${PIMILOR_FIREFOX_PATH}:/config
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]
