version: "3.9"
services:
  # Firefox (https://docs.linuxserver.io/images/docker-firefox)
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: pimilor-firefox
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${PIMILOR_FIREFOX_PORT:-3000}:3000
      - ${PIMILOR_FIREFOX_PORT_HTTPS:-3001}:3001
    security_opt:
      - seccomp:unconfined
    shm_size: "1gb"
    restart: unless-stopped
    volumes:
      - ${PIMILOR_FIREFOX_PATH:-./firefox}:/config
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - homepage.instance.admin.group=Pímilor
        - homepage.instance.admin.name=Firefox
        - homepage.instance.admin.description=Browser behind VPN
        - homepage.instance.admin.icon=firefox.svg
        - homepage.instance.admin.href=${PIMILOR_FIREFOX_URL:-http://localhost}
      placement:
        constraints: [node.labels.pimilor == true]

  # Huntarr (https://awesome-docker-compose.com/apps/arr/huntarr)
  huntarr:
    image: huntarr/huntarr:latest
    container_name: pimilor-huntarr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${PIMILOR_HUNTARR_PORT:-9705}:9705
    restart: unless-stopped
    volumes:
      - ${PIMILOR_HUNTARR_PATH:-./huntarr}:/config
    depends_on:
      - transmission
      - prowlarr
    deploy:
      labels:
        - homepage.instance.admin.group=Pímilor
        - homepage.instance.admin.name=Huntarr
        - homepage.instance.admin.description=Missing media manager
        - homepage.instance.admin.icon=huntarr.png
        - homepage.instance.admin.href=${PIMILOR_HUNTARR_URL:-http://localhost}
      placement:
        constraints: [node.labels.pimilor == true]

  # Lidarr (https://github.com/linuxserver/docker-lidarr)
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: pimilor-lidarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${PIMILOR_LIDARR_PORT:-8686}:8686
    restart: unless-stopped
    volumes:
      - ${PIMILOR_LIDARR_PATH:-./lidarr}:/config
      - thinmbahad-music:/music
      - cofbilion:/downloads
    depends_on:
      - transmission
      - prowlarr
    deploy:
      labels:
        - homepage.instance.admin.group=Pímilor
        - homepage.instance.admin.name=Lidarr
        - homepage.instance.admin.description=Book collection manager
        - homepage.instance.admin.icon=lidarr.svg
        - homepage.instance.admin.href=${PIMILOR_LIDARR_URL:-http://localhost}
        - homepage.instance.admin.widget.type=lidarr
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PIMILOR_LIDARR_PORT:-8686}
        - homepage.instance.admin.widget.key=${API_LIDARR:-changeMe}
        - homepage.instance.admin.widget.fields=["wanted", "queued", "artists"]
      placement:
        constraints: [node.labels.pimilor == true]

  # Mylar3 (https://github.com/mylar3/mylar3)
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: pimilor-mylar3
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${PIMILOR_MYLAR3_PORT:-8090}:8090
    restart: unless-stopped
    volumes:
      - ${PIMILOR_MYLAR3_PATH:-./mylar3}:/config
      - thinmbahad-comics:/comics
      - cofbilion:/downloads
    depends_on:
      - transmission
      - prowlarr
    deploy:
      labels:
        - homepage.instance.admin.group=Pímilor
        - homepage.instance.admin.name=Mylar3
        - homepage.instance.admin.description=Comic book collection manager
        - homepage.instance.admin.icon=sh-mylar3
        - homepage.instance.admin.href=${PIMILOR_MYLAR3_URL:-http://localhost}
        - homepage.instance.admin.widget.type=mylar
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PIMILOR_MYLAR3_PORT:-8090}
        - homepage.instance.admin.widget.key=${API_MYLAR3:-changeMe}
        - homepage.instance.admin.widget.fields=["series", "issues", "wanted"]
      placement:
        constraints: [node.labels.pimilor == true]

  # Overseerr (https://docs.linuxserver.io/images/docker-overseerr)
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: nethiadil-overseerr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      LOG_LEVEL: debug
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_OVERSEERR_PORT:-5055}:5055
    volumes:
      - ${PIMILOR_OVERSEERR_PATH:-./overseerr}:/config
    restart: unless-stopped
    depends_on:
      - transmission
      - sonarr
      - radarr
    deploy:
      labels:
        - homepage.instance.admin.group=Pímilor
        - homepage.instance.admin.name=Overseerr
        - homepage.instance.admin.description=Media request management
        - homepage.instance.public.group=Media
        - homepage.instance.public.description=Request TV shows and movies
        - homepage.instance.public.name=Plex Requests
        - homepage.icon=overseerr.svg
        - homepage.href=${PIMILOR_OVERSEERR_URL:-http://localhost}
        - homepage.widget.type=overseerr
        - homepage.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PIMILOR_OVERSEERR_PORT:-5055}
        - homepage.widget.key=${API_OVERSEERR:-changeMe}
        - homepage.widget.fields=["approved", "available", "processing"]
      placement:
        constraints: [node.labels.pimilor == true]

  # Prowlarr (https://github.com/linuxserver/docker-prowlarr)
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: pimilor-prowlarr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${PIMILOR_PROWLARR_PORT:-9696}:9696
    restart: unless-stopped
    volumes:
      - ${PIMILOR_PROWLARR_PATH:-./prowlarr}:/config
    depends_on:
      - transmission
    deploy:
      labels:
        - homepage.instance.admin.group=Pímilor
        - homepage.instance.admin.name=Prowlarr
        - homepage.instance.admin.description=Torrent indexer manager
        - homepage.instance.admin.icon=prowlarr.svg
        - homepage.instance.admin.href=${PIMILOR_PROWLARR_URL:-http://localhost}
        - homepage.instance.admin.widget.type=prowlarr
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PIMILOR_PROWLARR_PORT:-9696}
        - homepage.instance.admin.widget.key=${API_PROWLARR:-changeMe}
        - homepage.instance.admin.widget.fields=["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs", "numberOfFailQueries"]
      placement:
        constraints: [node.labels.pimilor == true]

  # Radarr (https://docs.linuxserver.io/images/docker-radarr)
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: pimilor-radarr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_RADARR_PORT:-7878}:7878
    restart: unless-stopped
    volumes:
      - ${PIMILOR_RADARR_PATH:-./radarr}:/config
      - thinmbahad-movies:/movies
      - cofbilion:/downloads
    depends_on:
      - transmission
      - prowlarr
    deploy:
      labels:
        - homepage.instance.admin.group=Pímilor
        - homepage.instance.admin.name=Radarr
        - homepage.instance.admin.description=Movie collection manager
        - homepage.instance.admin.icon=radarr.svg
        - homepage.instance.admin.href=${PIMILOR_RADARR_URL:-http://localhost}
        - homepage.instance.admin.widget.type=radarr
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PIMILOR_RADARR_PORT:-7878}
        - homepage.instance.admin.widget.key=${API_RADARR:-changeMe}
        - homepage.instance.admin.widget.fields=["wanted", "queued", "series"]
      placement:
        constraints: [node.labels.pimilor == true]

  # Sonarr (https://docs.linuxserver.io/images/docker-sonarr)
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: pimilor-sonarr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_SONARR_PORT:-8989}:8989
    restart: unless-stopped
    volumes:
      - ${PIMILOR_SONARR_PATH:-./sonarr}:/config
      - thinmbahad-tv:/tv
      - cofbilion:/downloads
    depends_on:
      - transmission
      - prowlarr
    deploy:
      labels:
        - homepage.instance.admin.group=Pímilor
        - homepage.instance.admin.name=Sonarr
        - homepage.instance.admin.description=TV show collection manager
        - homepage.instance.admin.icon=sonarr.svg
        - homepage.instance.admin.href=${PIMILOR_SONARR_URL:-http://localhost}
        - homepage.instance.admin.widget.type=sonarr
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PIMILOR_SONARR_PORT:-8989}
        - homepage.instance.admin.widget.key=${API_SONARR:-changeMe}
        - homepage.instance.admin.widget.fields=["wanted", "queued", "series"]
      placement:
        constraints: [node.labels.pimilor == true]

    # Transmission (https://docs.linuxserver.io/images/docker-transmission)
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: pimilor-transmission
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PEERPORT: ${PIMILOR_TRANSMISSION_PORT_INBOUND:-51413}
      TRANSMISSION_WEB_HOME: /config/ui/${PIMILOR_TRANSMISSION_WEBUI}
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_TRANSMISSION_PORT_UI:-9091}:9091
      - ${PIMILOR_TRANSMISSION_PORT_INBOUND:-51413}:51413
      - ${PIMILOR_TRANSMISSION_PORT_INBOUND:-51413}:51413/udp
    restart: unless-stopped
    volumes:
      - ${PIMILOR_TRANSMISSION_PATH:-./transmission}:/config
      - cofbilion:/downloads
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]
      resources:
        limits:
          cpus: "8.00"
          memory: 15G
        reservations:
          cpus: "6.00"
          memory: 9G

volumes:
  cofbilion:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${COFBILION_PATH}
  cofbilion-blackhole:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${COFBILION_PATH}/blackhole
  thinmbahad-tv:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/96.Video/96.05.TV
  thinmbahad-movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/96.Video/96.04.Movies
  thinmbahad-music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/91.Audio/91.01.Music
  thinmbahad-books:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/92.Books
  thinmbahad-ebooks:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/92.Books/92.04.eBooks
  thinmbahad-audiobooks:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/92.Books/92.01.Audiobooks
  thinmbahad-comics:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/92.Books/92.02.Comics
