version: "3.9"
services:

  # Firefox (https://docs.linuxserver.io/images/docker-firefox)
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: pimilor-firefox
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${PIMILOR_FIREFOX_PORT:-3000}:3000
      - ${PIMILOR_FIREFOX_PORT_HTTPS:-3001}:3001
    security_opt:
      - seccomp:unconfined
    shm_size: "1gb"
    restart: unless-stopped
    volumes:
      - ${PIMILOR_FIREFOX_PATH:-./firefox}:/config
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]

  # Transmission (https://docs.linuxserver.io/images/docker-transmission)
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: pimilor-transmission
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PEERPORT: ${PIMILOR_TRANSMISSION_PORT_INBOUND:-51413}
      TRANSMISSION_WEB_HOME: /config/ui/${PIMILOR_TRANSMISSION_WEBUI}
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_TRANSMISSION_PORT_UI:-9091}:9091
      - ${PIMILOR_TRANSMISSION_PORT_INBOUND:-51413}:51413
      - ${PIMILOR_TRANSMISSION_PORT_INBOUND:-51413}:51413/udp
    restart: unless-stopped
    volumes:
      - ${PIMILOR_TRANSMISSION_PATH:-./transmission}:/config
      - cofbilion:/downloads
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]
      resources:
        limits:
          cpus: '4.00'
          memory: 8G
        reservations:
          cpus: '2.00'
          memory: 6G

  # Sonarr (https://docs.linuxserver.io/images/docker-sonarr)
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: pimilor-sonarr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_SONARR_PORT:-8989}:8989
    restart: unless-stopped
    volumes:
      - ${PIMILOR_SONARR_PATH:-./sonarr}:/config
      - thinmbahad-tv:/tv
      - cofbilion:/downloads
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]

  # Radarr (https://docs.linuxserver.io/images/docker-radarr)
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: pimilor-radarr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_RADARR_PORT:-7878}:7878
    restart: unless-stopped
    volumes:
      - ${PIMILOR_RADARR_PATH:-./radarr}:/config
      - thinmbahad-movies:/movies 
      - cofbilion:/downloads
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]

  # Overseerr (https://docs.linuxserver.io/images/docker-overseerr)
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: nethiadil-overseerr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      LOG_LEVEL: debug
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_OVERSEERR_PORT:-5055}:5055
    volumes:
      - ${PIMILOR_OVERSEERR_PATH:-./overseerr}:/config
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]
  
  # Readarr (https://docs.linuxserver.io/images/docker-readarr)
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: pimilor-readarr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    logging:
      options:
        max-size: 10m
    ports:
      - ${PIMILOR_READARR_PORT:-8787}:8787
    restart: unless-stopped
    volumes:
      - ${PIMILOR_READARR_PATH:-./readarr}:/config
      - thinmbahad-ebooks:/books
      - cofbilion:/downloads
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]
  
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: pimilor-lidarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${PIMILOR_LIDARR_PORT:-8686}:8686
    restart: unless-stopped
    volumes:
      - ${PIMILOR_LIDARR_PATH:-./lidarr}:/config
      - thinmbahad-music:/music #optional
      - cofbilion:/downloads #optional
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]

  # Prowlarr (https://github.com/linuxserver/docker-prowlarr)
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: pimilor-prowlarr
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${PIMILOR_PROWLARR_PORT:-9696}:9696
    restart: unless-stopped
    volumes:
      - ${PIMILOR_PROWLARR_PATH:-./prowlarr}:/config
    deploy:
      placement:
        constraints: [node.labels.pimilor == true]



  # YTDL (https://github.com/Tzahi12345/YoutubeDL-Material)

volumes:
  cofbilion:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${COFBILION_PATH}
  cofbilion-audio:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${COFBILION_PATH}/public/audio
  cofbilion-blackhole:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${COFBILION_PATH}/blackhole
  cofbilion-movies:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${COFBILION_PATH}/public/movies
  cofbilion-tv:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${COFBILION_PATH}/public/tv
  cofbilion-video:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${COFBILION_PATH}/public/video
  thinmbahad-tv:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/tv
  thinmbahad-movies:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/movies
  thinmbahad-music:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/music
  thinmbahad-ebooks:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/books/ebooks
