version: "3.9"
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: angannondir-cloudflare
    cap_drop:
      - all
    environment:
      CF_API_TOKEN: ${ANGANNONDIR_CLOUDFLARE_TOKEN}
      DOMAINS: ${DOMAINS}
      PGID: ${PGID}
      PROXIED: "TRUE"
      PUID: ${PUID}
      TZ: ${TZ}
      IP6_PROVIDER: "none"
    network_mode: host
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    deploy:
      placement:
        constraints: [node.labels.angannondir == true]
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: angannondir-duckdns
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      SUBDOMAINS: ${ANGANNONDIR_DUCKDNS_SUBDOMAIN}
      TOKEN: ${ANGANNONDIR_DUCKDNS_TOKEN}
      LOG_FILE: "FALSE"
    restart: unless-stopped
    volumes:
      - ${ANGANNONDIR_DUCKDNS_PATH}:/config
    deploy:
      placement:
        constraints: [node.labels.angannondir == true]
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: angannondir-npm-app
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_NAME: ${ANGANNONDIR_DB_DATABASE}
      DB_MYSQL_PASSWORD: ${ANGANNONDIR_DB_PASSWORD}
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${ANGANNONDIR_DB_USERNAME}
      DISABLE_IPV6: "TRUE"
    ports:
      - ${ANGANNONDIR_NPM_PORT_HTTP}:80
      - ${ANGANNONDIR_NPM_PORT_HTTPS}:443
      - ${ANGANNONDIR_NPM_PORT_ADMIN}:81
    restart: always
    volumes:
      - ${ANGANNONDIR_NPM_PATH}/app:/data
      - ${ANGANNONDIR_NPM_PATH}/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.labels.angannondir == true]
  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: angannondir-npm-db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${ANGANNONDIR_DB_DATABASE}
      MYSQL_USER: ${ANGANNONDIR_DB_USERNAME}
      MYSQL_PASSWORD: ${ANGANNONDIR_DB_PASSWORD}
    restart: always
    volumes:
      - ${ANGANNONDIR_NPM_PATH}/database:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.labels.angannondir == true]
