version: "3.9"
services:

  # Kavita (https://www.kavitareader.com/)
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: perfadaben-kavita
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-America/New_York}
    ports:
      - ${PERFADABEN_KAVITA_PORT:-5000}:5000
    restart: unless-stopped
    volumes:
      - ${PERFADABEN_KAVITA_PATH:-./kavita}:/config
      - thinmbahad-books:/data/books
      - thinmbahad-comics:/data/comics
      - thinmbahad-magazines:/data/magazines
      - thinmbahad-rpgs:/data/rpgs
    deploy:
      placement:
        constraints: [node.labels.perfadaben == true]
  
  # Calibre (https://calibre-ebook.com/)
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: perfadaben-calibre
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-America/New_York}
      PASSWORD: ${PERFADABEN_CALIBRE_PASSWORD:-changeMe}
    ports:
      - ${PERFADABEN_CALIBRE_PORT:-8080}:8080
      - ${PERFADABEN_CALIBRE_PORT_SSL:-8181}:8181
      - ${PERFADABEN_CALIBRE_PORT_SERVER:-8081}:8081
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - thinmbahad-books-root:/config
    deploy:
      placement:
        constraints: [node.labels.perfadaben == true]

volumes:
  thinmbahad-books-root:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/books
  thinmbahad-books:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/books/ebooks
  thinmbahad-comics:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/books/comics
  thinmbahad-magazines:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/books/magazines
  thinmbahad-rpgs:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/books/rpgs
