version: "3.9"
services:
  # Audiobookshelf (https://www.audiobookshelf.org/)
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: perfadaben-audiobookshelf
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/New_York}
    ports:
      - ${PERFADABEN_AUDIOBOOKSHELF_PORT:-80}:80
    restart: unless-stopped
    volumes:
      - thinmbahad-audiobooks:/audiobooks
      - ${PERFADABEN_AUDIOBOOKSHELF_PATH:-./audiobookshelf}/config:/config
      - ${PERFADABEN_AUDIOBOOKSHELF_PATH:-./audiobookshelf}/metadata:/metadata
    deploy:
      labels:
        - homepage.instance.admin.group=Perfadaben
        - homepage.instance.admin.name=Audiobookshelf
        - homepage.instance.admin.description=Audiobook player
        - homepage.icon=audiobookshelf.svg
        - homepage.href=${PERFADABEN_AUDIOBOOKSHELF_URL:-http://localhost}
        - homepage.instance.public.group=Library
        - homepage.instance.public.name=Audiobooks
        - homepage.instance.admin.widget.type=audiobookshelf
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PERFADABEN_AUDIOBOOKSHELF_PORT:-80}
        - homepage.instance.admin.widget.key=${API_AUDIOBOOKSHELF:-changeMe}
        - homepage.instance.admin.widget.fields=["books", "booksDuration"]
      placement:
        constraints: [node.hostname == budhlefnui]

  # Calibre (https://calibre-ebook.com/)
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: perfadaben-calibre
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-America/New_York}
      CUSTOM_USER: ${PERFADABEN_CALIBRE_USERNAME:-admin}
      PASSWORD: ${PERFADABEN_CALIBRE_PASSWORD:-changeMe}
      TITLE: "Calibre"
    ports:
      - ${PERFADABEN_CALIBRE_PORT:-8080}:8080
      - ${PERFADABEN_CALIBRE_PORT_SSL:-8181}:8181
      - ${PERFADABEN_CALIBRE_PORT_SERVER:-8081}:8081
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - ${PERFADABEN_CALIBRE_PATH:-./calibre}:/config
      - thinmbahad-books:/config/Calibre Library
    deploy:
      labels:
        - homepage.instance.admin.group=Perfadaben
        - homepage.instance.admin.name=Calibre
        - homepage.instance.admin.description=Audiobook and eBook management
        - homepage.instance.admin.icon=calibre.svg
        - homepage.instance.admin.href=${PERFADABEN_CALIBRE_URL:-http://localhost}
      placement:
        constraints: [node.hostname == budhlefnui]

  # Calibre (https://calibre-ebook.com/)
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: perfadaben-calibre-web
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-America/New_York}
    ports:
      - ${PERFADABEN_CALIBRE_WEB_PORT:-8083}:8083
    restart: unless-stopped
    volumes:
      - ${PERFADABEN_CALIBRE_WEB_PATH:-./calibre-web}:/config
      - ${PERFADABEN_CALIBRE_PATH:-./calibre}:/books
    deploy:
      labels:
        - homepage.instance.admin.group=Perfadaben
        - homepage.instance.admin.name=Calibre Web
        - homepage.instance.public.group=Library
        - homepage.instance.public.name=eBooks
        - homepage.description=eBook reader
        - homepage.icon=calibre-web.svg
        - homepage.href=${PERFADABEN_CALIBRE_WEB_URL:-http://localhost}
        - homepage.instance.admin.widget.type=calibreweb
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PERFADABEN_CALIBRE_WEB_PORT:-80}
        - homepage.instance.admin.widget.fields=["books", "authors", "categories", "series"]
      placement:
        constraints: [node.hostname == budhlefnui]

  kavita:
    image: jvmilazz0/kavita:latest # Using the stable branch from the official dockerhub repo.
    container_name: perfadaben-kavita
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${PERFADABEN_KAVITA_PORT:-5000}:5000
    restart: unless-stopped
    volumes:
      - thinmbahad-comics:/comics
      - ${PERFADABEN_KAVITA_PATH}:/kavita/config
    deploy:
      labels:
        - homepage.instance.admin.group=Perfadaben
        - homepage.instance.admin.name=Kavita
        - homepage.instance.public.group=Library
        - homepage.instance.public.name=Comicbooks
        - homepage.description=Comic book reader
        - homepage.icon=kavita.svg
        - homepage.href=${PERFADABEN_KAVITA_URL:-http://localhost}
        - homepage.instance.admin.widget.type=kavita
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${PERFADABEN_KAVITA_PORT:-5000}
        - homepage.instance.admin.widget.key=${API_KAVITA:-changeMe}
        - homepage.instance.admin.widget.fields=["seriesCount", "totalFiles"]
      placement:
        constraints: [node.hostname == budhlefnui]

volumes:
  thinmbahad-books:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/92.Books
  thinmbahad-ebooks:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/92.Books/92.04.eBooks
  thinmbahad-audiobooks:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/92.Books/92.01.Audiobooks
  thinmbahad-comics:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/92.Books/92.02.Comics
