version: "3.9"
services:
  expos_wordpress:
    image: wordpress:6.6.1-php8.3-fpm
    container_name: comenbyr-wordpress
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: ${COMENBYR_EXPOS_WORDPRESS_DB_NAME:-npm}
      WORDPRESS_DB_PASSWORD: ${ROOT_PASSWORD:-npm}
      WORDPRESS_DB_USER: ${ROOT_USERNAME:-npm}
    networks:
      - gulhir
    ports:
      - ${COMENBYR_EXPOS_WORDPRESS_PORT:-80}:80
    restart: always
    volumes:
      - ${COMENBYR_EXPOS_WORDPRESS_PATH:-./wordpress}/app:/var/www/html
    
networks:
  gulhir:
    external: true
