version: "3.9"
services:
  # MySQL/MariaDB (https://github.com/yobasystems/alpine-mariadb)
  mysql:
    image: yobasystems/alpine-mariadb:latest
    container_name: goistor-mysql
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-changeMe}
      MYSQL_USER: ${ROOT_USERNAME:-root}
      MYSQL_PASSWORD: ${ROOT_PASSWORD:-changeMe}
    networks:
      - gulhir
    ports:
      - ${GOISTOR_MYSQL_PORT:-3306}:3306
    restart: always
    volumes:
      - ${GOISTOR_MYSQL_PATH:-./mysql}:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.labels.goistor == true]

  # PHPMyAdmin (https://github.com/phpmyadmin/docker)
  phpmyadmin:
    image: phpmyadmin:apache
    container_name: goistor-phpmyadmin
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PMA_HOST: mysql
    networks:
      - gulhir
    ports:
      - ${GOISTOR_PHPMYADMIN_PORT:-8080}:80
    restart: always
    volumes:
      - /sessions
    deploy:
      placement:
        constraints: [node.labels.goistor == true]

  # Postgres (https://hub.docker.com/_/postgres)
  postgres:
    image: postgres:16.4
    container_name: goistor-postgres
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      POSTGRES_USER: ${ROOT_USERNAME:-changeMe}
      POSTGRES_PASSWORD: ${ROOT_PASSWORD:-changeMe}
      POSTGRES_DB: ${ROOT_USERNAME:-changeMe}
    networks:
      - gulhir
    ports:
      - ${GOISTOR_POSTGRES_PORT:-5432}:5432
    restart: always
    volumes:
      - ${GOISTOR_POSTGRES_PATH:-./postgres}:/var/lib/postgresql/data/
    deploy:
      placement:
        constraints: [node.labels.goistor == true]

  # PGAdmin (https://www.pgadmin.org)
  postgres-admin:
    image: dpage/pgadmin4
    container_name: goistor-postgres-admin
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PGADMIN_DEFAULT_EMAIL: ${ROOT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${ROOT_PASSWORD:-changeMe}
    networks:
      - gulhir
    ports:
      - ${GOISTOR_POSTGRES_ADMIN_PORT:-15432}:80
    restart: always
    volumes:
      - ${GOISTOR_POSTGRES_ADMIN_PATH:-./postgres-admin}:/var/lib/pgadmin/
    depends_on:
      - postgres
    deploy:
      placement:
        constraints: [node.labels.goistor == true]

  # Redis (https://github.com/docker-library/redis)
  redis:
    image: redis:6.2-alpine
    container_name: goistor-redis
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    networks:
      - gulhir
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: always
    volumes:
      - ${GOISTOR_REDIS_PATH:-./redis}:/data
    deploy:
      placement:
        constraints: [node.labels.goistor == true]
  
  # Minio (https://min.io)
  minio:
    image: docker.io/bitnami/minio:latest
    container_name: goistor-minio
    environment:
      MINIO_ROOT_USER: ${ROOT_USERNAME:-changeMe}
      MINIO_ROOT_PASSWORD: ${ROOT_PASSWORD:-changeMe}
      MINIO_DEFAULT_BUCKETS: ${GOISTOR_MINIO_BUCKET:-gulhir}
    networks:
      - gulhir
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_PORT_SSL:-9001}:9001
    restart: always
    volumes:
      - thinmbahad-storage:/data
    deploy:
      placement:
        constraints: [node.labels.goistor == true]
    

networks:
  gulhir:
    external: true

volumes:
  thinmbahad-storage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/storage