version: "3.9"
services:
  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: goistor-db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${GOISTOR_DB_USERNAME}
      MYSQL_PASSWORD: ${GOISTOR_DB_PASSWORD}
    restart: always
    volumes:
      - ${GOISTOR_DB_PATH}:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.labels.goistor == true]

  sheetable:
    image: vallezw/sheetable
    container_name: goistor-sheetable
    environment:
      CONFIG_PATH: /app/config/
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    restart: unless-stopped
    ports:
      - ${GOISTOR_SHEETABLE_PORT}:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GOISTOR_SHEETABLE_PATH}:/app/config
    deploy:
      placement:
        constraints: [node.labels.goistor == true]

  monica-app:
    image: monica
    container_name: monica-app
    environment:
      # APP_KEY:
      DB_HOST: db
      DB_DATABASE: ${GOISTOR_MONICA_DATABASE}
      DB_PORT: 3306
      DB_USERNAME: ${GOISTOR_DB_USERNAME}
      DB_PASSWORD: ${GOISTOR_DB_PASSWORD}
    ports:
      - ${GOISTOR_MONICA_PORT}:80
    restart: always
    volumes:
      - ${GOISTOR_MONICA_PATH}:/var/www/html/storage
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.labels.goistor == true]

  # TODO Find bookmarking link

  # TODO https://github.com/partkeepr/PartKeepr/blob/master/docker/development/docker-compose.yml
  # partkeepr:
  #   image: mhubig/partkeepr:latest
  #   container_name: goistor-partkeepr
  #   environment:
  #     PARTKEEPR_DATABASE_HOST: db
  #     PARTKEEPR_DATABASE_NAME: ${GOISTOR_PARTKEEPR_DATABASE}
  #     PARTKEEPR_DATABASE_PORT: 3306
  #     PARTKEEPR_DATABASE_USER: ${GOISTOR_DB_USERNAME}
  #     PARTKEEPR_DATABASE_PASS: ${GOISTOR_DB_PASSWORD}
  #     PARTKEEPR_SECRET: ${GOISTOR}
  #   ports:
  #     - ${GOISTOR_PARTKEEPR_PORT}:80
  #   restart: on-failure
  #   volumes:
  #     - ${GOISTOR_PARTKEEPR_PATH}/config:/var/www/html/app/config
  #     - ${GOISTOR_PARTKEEPR_PATH}:/var/www/html/data
  #     - ${GOISTOR_PARTKEEPR_PATH}/web:/var/www/html/web
  #   depends_on:
  #     - db
  #   deploy:
  #     placement:
  #       constraints: [node.labels.goistor == true]

  # cronjob:
  #   image: mhubig/partkeepr:latest
  #   container_name: goistor-partkeepr-cronjob
  #   command: bash -c "crontab /etc/cron.d/partkeepr && cron -f"
  #   entrypoint: []
  #   restart: on-failure
  #   volumes:
  #     - ${GOISTOR_PARTKEEPR_PATH}/config:/var/www/html/app/config:ro
  #     - ${GOISTOR_PARTKEEPR_PATH}:/var/www/html/data
  #     - ${GOISTOR_PARTKEEPR_PATH}/web:/var/www/html/web
  #   depends_on:
  #     - partkeepr
  #   deploy:
  #     placement:
  #       constraints: [node.labels.goistor == true]
