plugins: fetchart embedart convert scrub replaygain lastgenre chroma web discogs missing the
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: yes
per_disc_numbering: no

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1

paths:
    default: %the{$albumartist}/$album%aunique{} ($original_year)/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: yes
    move: yes
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

chroma:
    auto: yes

acoustid:
    apikey: W4lF8LUz5Q

discogs:
    user_token: "gPwynJJjFXPsWBJAFSaFDhfkLRvpqVMZVJwTRtix"
    index_tracks: yes
    source_weight: 0.1

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    enforce_ratio: yes
    sources: coverart itunes albumart wikipedia amazon
    cover_names: front cover album

missing:
    format: $albumartist - $album - $title
    count: yes
    total: no

replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337