---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "KazJo.com"
subtitle: "Dashboard Deluxe"
logo: "logo.svg"
# icon: "fas fa-leaf"
header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#1DB6A4"
    highlight-secondary: "#3CD6C4"
    highlight-hover: "#70E5D8"
    background: "#F2F0F0"
    card-background: "#ffffff"
    text: "#0B2E2A"
    text-header: "#ffffff"
    text-title: "#061715"
    text-subtitle: "#5E6B6A"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#1DB6A4"
    link-hover: "#18998A"
  dark:
    highlight-primary: "#1DB6A4"
    highlight-secondary: "#3CD6C4"
    highlight-hover: "#70E5D8"
    background: "#072E29"
    card-background: "#5E6B6A"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#F2F0F0"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#1DB6A4"
    link-hover: "#22D6C1"

# # Optional message
# message:
#   #url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   icon: "fa fa-grin"
#   content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
# links:
#   - name: "Contribute"
#     icon: "fab fa-github"
#     url: "https://github.com/bastienwirtz/homer"
#     target: "_blank" # optional html a tag target attribute
#   - name: "Wiki"
#     icon: "fas fa-book"
#     url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Xanadu"
    icon: "fas fa-home-lg"
    items:
      - name: "Cookbook"
        logo: "assets/tools/mealie.png"
        subtitle: "Powered by Mealie"
        # tag: "app"
        keywords: "recipe cookbook xanadu mealie"
        url: "https://cookbook.kazjo.co"
        target: "_blank"
  - name: "Plex Media Server"
    icon: "fas fa-camera-movie"
    items:
      - name: "Plex Media Server"
        logo: "assets/tools/plex-icon.png"
        subtitle: "Login required."
        # tag: "app"
        keywords: "plex media server movie tv video"
        url: "https://plex.kazjo.co"
        target: "_blank"
      - name: "Request TV shows and movies"
        logo: "assets/tools/ombi.png"
        subtitle: "Plex login required."
        # tag: "app"
        keywords: "plex media server movie tv video request ombi"
        url: "https://requests.kazjo.co"
        target: "_blank"
