version: "3.9"
services:
  # Crafty (https://craftycontrol.com)
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: lavanoveren-crafty
    environment:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
        TZ: ${TZ:-America/Los_Angeles}
    ports:
        - ${LAVANOVEREN_CRAFTY_PORT_UI:-8000}:8000
        - ${LAVANOVEREN_CRAFTY_PORT_SOCKET:-8123}:8123
        - ${LAVANOVEREN_CRAFTY_PORT_BEDROCK:-19132}:19132/udp
        - ${LAVANOVEREN_CRAFTY_PORT_JAVA_RANGE:-25500-25600}:25500-25600
    restart: always
    volumes:
        - ${LAVANOVEREN_CRAFTY_PATH:-./crafty}/backups:/crafty/backups
        - ${LAVANOVEREN_CRAFTY_PATH:-./crafty}/logs:/crafty/logs
        - ${LAVANOVEREN_CRAFTY_PATH:-./crafty}/servers:/crafty/servers
        - ${LAVANOVEREN_CRAFTY_PATH:-./crafty}/config:/crafty/app/config
        - ${LAVANOVEREN_CRAFTY_PATH:-./crafty}/import:/crafty/import
    deploy:
      labels:
        - homepage.instance.admin.group=Lavanoveren
        - homepage.instance.admin.name=Crafty Controller
        - homepage.instance.public.group=Games
        - homepage.instance.public.name=Minecraft
        - homepage.description=Minecraft server manager
        - homepage.icon=crafty-controller.svg
        - homepage.href=${LAVANOVEREN_CRAFTY_URL:-http://localhost}
      placement:
        constraints: [node.labels.lavanoveren_minecraft == true]

  # Foundry VTT (https://github.com/felddy/foundryvtt-docker)
  foundry-vtt:
    image: felddy/foundryvtt:latest
    container_name: lavanoveren-foundryvtt
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      FOUNDRY_PASSWORD: ${LAVANOVEREN_FOUNDRYVTT_PASSWORD:-changeMe}
      FOUNDRY_USERNAME: ${LAVANOVEREN_FOUNDRYVTT_USERNAME:-admin}
      FOUNDRY_ADMIN_KEY: ${LAVANOVEREN_FOUNDRYVTT_KEY:-1234567890}
    hostname: ${LAVANOVEREN_FOUNDRYVTT_HOSTNAME:-Foundry}
    init: true
    ports:
      - ${LAVANOVEREN_FOUNDRYVTT_PORT:-3000}:30000
    volumes:
      - ${LAVANOVEREN_FOUNDRYVTT_PATH:-./foundry}:/data
    deploy:
      labels:
        - homepage.instance.admin.group=Lavanoveren
        - homepage.instance.admin.name=Foundry VTT
        - homepage.instance.public.group=Games
        - homepage.instance.public.name=Foundry Virtual Tabletop
        - homepage.description=Virtual tabletop for role-playing games
        - homepage.icon=si-foundryvirtualtabletop
        - homepage.href=${LAVANOVEREN_FOUNDRYVTT_URL:-http://localhost}
      placement:
        constraints: [node.labels.lavanoveren == true]

  # Gaseous (https://github.com/gaseous-project/gaseous-server)
  gaseous:
    image: gaseousgames/gaseousserver:latest
    container_name: lavanoveren-gaseous
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      dbhost: mysql
      dbuser: ${ROOT_USERNAME:-root}
      dbpass: ${ROOT_PASSWORD:-changeMe}
      igdbclientid: ${LAVANOVEREN_GASEOUS_CLIENT_ID:-changeMe}
      igdbclientsecret: ${LAVANOVEREN_GASEOUS_CLIENT_SECRET:-changeMe}
    networks:
      - gulhir
    ports:
      - ${LAVANOVEREN_GASEOUS_PORT:-80}:80
    restart: unless-stopped
    volumes:
      - ${LAVANOVEREN_GASEOUS_PATH:-./gaseous}:/root/.gaseous-server
      - thinmbahad-roms:/root/roms
    depends_on:
      - mysql
    deploy:
      labels:
        - homepage.instance.admin.group=Lavanoveren
        - homepage.instance.admin.name=Gaseous
        - homepage.instance.admin.description=Game library management
        - homepage.instance.admin.icon=gaseous.png
        - homepage.instance.admin.href=${LAVANOVEREN_GASEOUS_URL:-http://localhost}
      placement:
        constraints: [node.labels.lavanoveren == true]

networks:
  gulhir:
    external: true

volumes:
  thinmbahad-roms:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/93.Games/93.01.ROMs