version: "3.9"
services:

  # Minecraft (https://github.com/itzg/docker-minecraft-server)
  # CurseForce Modpacks (https://legacy.curseforge.com/minecraft/modpacks)
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: lavanoveren-minecraft
    environment:
      CF_API_KEY: ${LAVANOVEREN_MINECRAFT_CURSEFORGE_API:-1234567890}
      ALLOW_CHEATS: "TRUE"
      DIFFICULTY: normal
      EULA: "TRUE"
      GAMEMODE: SURVIVAL
      GENERATE_STRUCTURES: "TRUE"
      GID: ${PGID:-1000}
      LEVEL_NAME: ${LAVANOVEREN_MINECRAFT_LEVEL_NAME:-Level}
      MAX_PLAYERS: 100
      MEMORY: 8G
      MOTD: ${LAVANOVEREN_MINECRAFT_MOTD:-Oh hello there}
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      SERVER_NAME: ${LAVANOVEREN_MINECRAFT_SERVER_NAME:-Server}
      TYPE: FORGE
      TZ: ${TZ:-America/Los_Angeles}
      UID: ${PUID:-1000}
    ports:
      - ${LAVANOVEREN_MINECRAFT_PORT:-25565}:25565
    stdin_open: true
    tty: true
    volumes:
      - ${LAVANOVEREN_MINECRAFT_PATH:-./minecraft}/app:/data
      - ${LAVANOVEREN_MINECRAFT_PATH:-./minecraft}/mods:/mods:ro
      - ${LAVANOVEREN_MINECRAFT_PATH:-./minecraft}/modpacks:/modpacks:ro
    deploy:
      placement:
        constraints: [node.labels.lavanoveren_minecraft == true]

  # Foundry VTT (https://github.com/felddy/foundryvtt-docker)
  foundry-vtt:
    image: felddy/foundryvtt:latest
    container_name: lavanoveren-foundryvtt
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      FOUNDRY_PASSWORD: ${LAVANOVEREN_FOUNDRYVTT_PASSWORD:-changeMe}
      FOUNDRY_USERNAME: ${LAVANOVEREN_FOUNDRYVTT_USERNAME:-admin}
      FOUNDRY_ADMIN_KEY: ${LAVANOVEREN_FOUNDRYVTT_KEY:-1234567890}
    hostname: ${LAVANOVEREN_FOUNDRYVTT_HOSTNAME:-Foundry}
    init: true
    ports:
      - ${LAVANOVEREN_FOUNDRYVTT_PORT:-3000}:30000
    volumes:
      - ${LAVANOVEREN_FOUNDRYVTT_PATH:-./foundry}:/data
    deploy:
      placement:
        constraints: [node.labels.lavanoveren == true]