version: "3"
services:
  migrations:
    image: mediacms/mediacms:latest
    container_name: faenil-mediacms-migrations
    command: "${FAENIL_MEDIACMS_PATH}/deploy/docker/prestart.sh"
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: ${FAENIL_MEDIACMS_USER}
      ADMIN_EMAIL: ${EMAIL_ADDRESS}
      ADMIN_PASSWORD: ${FAENIL_MEDIACMS_PASSWORD}
    restart: on-failure
    volumes:
      - ${FAENIL_MEDIACMS_PATH}/deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    depends_on:
      - redis
      - db
    deploy:
      placement:
        constraints: [node.labels.faenil == true]
  web:
    image: mediacms/mediacms:latest
    container_name: faenil-mediacms-app
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    ports:
      - ${FAENIL_MEDIACMS_PORT}:80
    volumes:
      - mediacms-media:/home/mediacms.io/mediacms/media_files/
      - ${FAENIL_MEDIACMS_PATH}/static:/home/mediacms.io/mediacms/static/
      - ${FAENIL_MEDIACMS_PATH}/deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    depends_on:
      - migrations
    deploy:
      placement:
        constraints: [node.labels.faenil == true]

  celery_beat:
    image: mediacms/mediacms:latest
    container_name: faenil-mediacms-celerybeat
    volumes:
      - ${FAENIL_MEDIACMS_PATH}/deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
    deploy:
      placement:
        constraints: [node.labels.faenil == true]

  celery_worker:
    image: mediacms/mediacms:latest
    container_name: faenil-mediacms-celeryworker
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    volumes:
      - mediacms-media:/home/mediacms.io/mediacms/media_files/
      - ${FAENIL_MEDIACMS_PATH}/static:/home/mediacms.io/mediacms/static/
      - ${FAENIL_MEDIACMS_PATH}/deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    depends_on:
      - migrations
    deploy:
      placement:
        constraints: [node.labels.faenil == true]

  db:
    image: postgres:13
    container_name: faenil-mediacms-db
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediacms"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - ${FAENIL_MEDIACMS_PATH}/database:/var/lib/postgresql/data/
    deploy:
      placement:
        constraints: [node.labels.faenil == true]

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    deploy:
      placement:
        constraints: [node.labels.faenil == true]

volumes:
  mediacms-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${COFBILION_PATH}/.db/faenil/mediacms/gallery
