version: "3.9"
services:
  firefly:
    image: fireflyiii/core:latest
    container_name: celebwain-firefly
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      ALLOW_WEBHOOKS: "TRUE"
      APP_DEBUG: "TRUE"
      APP_KEY: ${CELEBWAIN_FIREFLY_KEY:-changeMe}
      APP_URL: ${CELEBWAIN_FIREFLY_URL:-http://localhost}
      CACHE_DRIVER: redis
      DB_CONNECTION: pgsql
      DB_DATABASE: ${CELEBWAIN_FIREFLY_DATABASE:-firefly}
      DB_HOST: postgres
      DB_PASSWORD: ${ROOT_PASSWORD:-changeMe}
      DB_PORT: ${POSGRES_PORT:-5432}
      DB_USERNAME: ${ROOT_USERNAME:-changeMe}
      REDIS_HOST: ${REDIS_URL:-redis://localhost:6379}
      SESSION_DRIVER: redis
      SITE_OWNER: ${ROOT_EMAIL:-admin@localhost}
      TRUSTED_PROXIES: "**"
    hostname: firefly
    networks:
      - gulhir
    ports:
      - ${CELEBWAIN_FIREFLY_PORT:-8080}:8080
    restart: always
    volumes:
      - ${CELEBWAIN_FIREFLY_PATH:-./fireflyiii}:/var/www/html/storage/upload
    depends_on:
      - postgres
      - redis
    deploy:
      labels:
        - homepage.instance.admin.group=Celebwain
        - homepage.instance.admin.name=Firefly III
        - homepage.instance.admin.description=Finance manager
        - homepage.instance.admin.icon=firefly-iii.svg
        - homepage.instance.admin.href=${CELEBWAIN_FIREFLY_URL:-http://localhost}
        - homepage.widget.type=firefly
        - homepage.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${CELEBWAIN_FIREFLY_PORT:-8080}
        - homepage.widget.key=${CELEBWAIN_FIREFLY_TOKEN:-changeMe}
        - homepage.widget.fields=["networth" ,"budget"]
      placement:
        constraints: [node.hostname == nadhrawlos]

  firefly_cron:
    image: alpine
    container_name: celebwain-firefly-cron
    command: sh -c "
      apk add tzdata && \
      ln -fs /usr/share/zoneinfo/$$TZ /etc/localtime && \
      echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      STATIC_CRON_TOKEN: ${CELEBWAIN_FIREFLY_KEY:-changeMe}
    networks:
      - gulhir
    restart: always
    depends_on:
      - firefly
    deploy:
      labels:
        - homepage.instance.admin.group=Celebwain
        - homepage.instance.admin.name=Firefly III Crontab
        - homepage.instance.admin.description=Cron jobs for Firefly III
        - homepage.instance.admin.icon=firefly-iii.svg
      placement:
        constraints: [node.hostname == nadhrawlos]
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: celebwain-paperless-ngx
    environment:
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_REDIS: ${REDIS_URL:-redis://redis:6379}/${REDIS_DB_PAPERLESS:-0}
      PAPERLESS_SECRET_KEY: ${CELEBWAIN_PAPERLESS_SECRET_KEY:-changeMe}
      PAPERLESS_TIME_ZONE: ${TZ:-America/Los_Angeles}
      PAPERLESS_URL: ${CELEBWAIN_PAPERLESS_URL:-http://localhost}
      USERMAP_GID: ${PGID:-1000}
      USERMAP_UID: ${PUID:-1000}
    networks:
      - gulhir
    ports:
      - ${CELEBWAIN_PAPERLESS_PORT:-8000}:8000
    restart: unless-stopped
    volumes:
      - ${CELEBWAIN_PAPERLESS_PATH:-./paperless}:/usr/src/paperless/data
      - thinmbahad-paperless-storage:/usr/src/paperless/media
      - thinmbahad-paperless-export:/usr/src/paperless/export
      - thinmbahad-paperless-import:/usr/src/paperless/consume
    depends_on:
      - redis
    deploy:
      labels:
        - homepage.instance.admin.group=Nanuchebwe
        - homepage.instance.public.group=Organization
        - homepage.instance.name=Paperless
        - homepage.instance.description=Document management system
        - homepage.instance.icon=paperless-ngx
        - homepage.instance.href=${CELEBWAIN_PAPERLESS_URL:-http://localhost}
        - homepage.instance.admin.widget.type=paperlessngx
        - homepage.instance.admin.widget.url=http://${RAEDORVUDH_IP:-http://localhost}:${CELEBWAIN_PAPERLESS_PORT:-8000}
        - homepage.instance.admin.widget.key=${API_PAPERLESS:-changeMe}
        - homepage.instance.admin.widget.fields=["total", "inbox"]
      placement:
        constraints: [node.hostname == amonvedui]

networks:
  gulhir:
    external: true

volumes:
  thinmbahad-paperless-export:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/95.Storage/95.03.paperless/export
  thinmbahad-paperless-import:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/95.Storage/95.03.paperless/consume
  thinmbahad-paperless-storage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/95.Storage/95.03.paperless/media