version: "3.9"
services:

  # Firefly III (https://github.com/firefly-iii/firefly-iii)
  fireflyiii-app:
    image: fireflyiii/core:latest
    container_name: celebwain-fireflyiii-app
    environment:
      # IMPORT_DIR_ALLOWLIST: 
      # JSON_CONFIGURATION_DIR: 
      APP_DEBUG: "FALSE"
      APP_ENV: local
      APP_KEY: ${CELEBWAIN_FIREFLYIII_APP_KEY:-changeMeto32CharacterString}
      AUTO_IMPORT_SECRET: ${CELEBWAIN_FIREFLYIII_SECRET_KEY:-changeMe}
      CAN_POST_AUTOIMPORT: "TRUE"
      CAN_POST_FILES: "TRUE"
      CONNECTION_TIMEOUT: 31.41
      FIREFLY_III_ACCESS_TOKEN: ${CELEBWAIN_FIREFLYIII_ACCESS_TOKEN:-changeMe}
      FIREFLY_III_CLIENT_ID: ${CELEBWAIN_FIREFLYIII_CLIENT_ID:-1234}
      FIREFLY_III_URL: http://${RAEDORVUDH_IP:-127.0.0.1}:${CELEBWAIN_FIREFLYIII_PORT:-8080}
      IGNORE_DUPLICATE_ERRORS: "TRUE"
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      PGID: ${PGID}
      PUID: ${PUID}
      TRUSTED_PROXIES: '**'
      TZ: ${TZ}
      USE_CACHE: "TRUE"
      VANITY_URL: ${CELEBWAIN_FIREFLYIII_URL:-http://localhost}
      VERIFY_TLS_SECURITY: "TRUE"
    ports:
      - ${CELEBWAIN_FIREFLYIII_PORT:-8080}:8080
    restart: always
    volumes:
      - ${CELEBWAIN_FIREFLYIII_PATH:-./firefly-iii}:/var/www/html/storage/upload
    depends_on:
      - fireflyiii-db
    deploy:
      placement:
        constraints: [node.labels.celebwain == true]

  fireflyiii-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: celebwain-fireflyiii-db
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-changeMe}
      MYSQL_DATABASE: ${CELEBWAIN_FIREFLYIII_DATABASE:-fireflyiii}
      MYSQL_USER: ${ROOT_USERNAME:-npm}
      MYSQL_PASSWORD: ${ROOT_PASSWORD:-npm}
    network_mode: "service:goistor_mysql"
    restart: always
    deploy:
      placement:
        constraints: [node.labels.goistor == true]
  
  # Nano Wallet (https://github.com/linuxserver/nano-wallet)
  nano-wallet:
    image: lscr.io/linuxserver/nano-wallet:latest
    container_name: celebwain-nano-wallet
    ports:
      - ${CELEBWAIN_NANO_WALLET_PORT:-80}:80
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.labels.celebwain == true]

