---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "KazJo.com"
subtitle: "Dashboard Deluxe"
logo: "logo.svg"
header: true
footer: false

columns: "3"
connectivityCheck: true

defaults:
  layout: columns
  colorTheme: light

stylesheet:
  - "assets/tish.css"



# --- Colors and styles ------ #
theme: default
colors:
  light:
    highlight-primary: "#E6EDEC"
    highlight-secondary: "#D0D6D5"
    highlight-hover: "#70E5D8"
    background: "#F2F0F0"
    card-background: "#ffffff"
    text: "#0B2E2A"
    text-header: "#ffffff"
    text-title: "#061715"
    text-subtitle: "#5E6B6A"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#1DB6A4"
    link-hover: "#18998A"
  dark:
    highlight-primary: "#1DB6A4"
    highlight-secondary: "#3CD6C4"
    highlight-hover: "#70E5D8"
    background: "#072E29"
    card-background: "#5E6B6A"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#F2F0F0"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#1DB6A4"
    link-hover: "#22D6C1"


# # Optional message
# message:
#   #url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   icon: "fa fa-grin"
#   content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
# links:
#   - name: "Contribute"
#     icon: "fab fa-github"
#     url: "https://github.com/bastienwirtz/homer"
#     target: "_blank" # optional html a tag target attribute
#   - name: "Wiki"
#     icon: "fas fa-book"
#     url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"



services:

  - name: Aesordúr
    items:
      - name: "Mealie"
        logo: "assets/tools/mealie.png"
        url: "https://cookbook.kazjo.co"
        target: "_blank"


  - name: Angannondír
    items:
      - name: "NGINX Proxy Manager"
        logo: "assets/tools/proxy_mgr.png"
        url: "https://npm.kazjo.co"
        target: "_blank"

      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        url: "https://angannondir.kazjo.co"
        target: "_blank"

  - name: Celebwain
    items:
      - name: "Firefly III"
        logo: "assets/tools/mealie.png"
        subtitle: ""
        url: ""
        target: "_blank"


  - name: Erebithron
    items:
      - name: "Hedgedoc"
        logo: "assets/tools/mealie.png"
        url: "https://notes.kazjo.co"
        target: "_blank"

      - name: "Gitea"
        logo: "assets/tools/gitea.png"
        url: "https://git.kazjo.co"
        target: "_blank"

      - name: "Snippet Box"
        logo: "assets/tools/snibox.png"
        url: "https://snippets.kazjo.co"
        target: "_blank"


  - name: Goistor
    icons: ""
    items:
      - name: "NGINX Proxy Manager"
        logo: "assets/tools/mealie.png"
        subtitle: ""
        url: ""
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/mealie.png"
        subtitle: ""
        url: ""
        target: "_blank"

  - name: Lavanoveren
    icons: ""
    items:
      - name: "NGINX Proxy Manager"
        logo: "assets/tools/mealie.png"
        subtitle: ""
        url: ""
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/mealie.png"
        subtitle: ""
        url: ""
        target: "_blank"

  - name: Mirdadhraeg
    icons: ""
    items:
      - name: "NGINX Proxy Manager"
        logo: "assets/tools/mealie.png"
        subtitle: ""
        url: ""
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/mealie.png"
        subtitle: ""
        url: ""
        target: "_blank"


  - name: Nethiadil
    icons: ""
    items:
      - name: "Mealie"
        logo: "assets/tools/mealie.png"
        subtitle: "Powered by Mealie"
        url: "https://cookbook.kazjo.co"
        target: "_blank"


  - name: Perfadaben
    icons: ""
    items:
      - name: "Mealie"
        logo: "assets/tools/mealie.png"
        subtitle: "Powered by Mealie"
        url: "https://cookbook.kazjo.co"
        target: "_blank"


  - name: Pímilor
    icons: ""
    items:
      - name: "Mealie"
        logo: "assets/tools/mealie.png"
        subtitle: "Powered by Mealie"
        url: "https://cookbook.kazjo.co"
        target: "_blank"
      - name: "Mealie"
        logo: "assets/tools/mealie.png"
        subtitle: "Powered by Mealie"
        url: "https://cookbook.kazjo.co"
        target: "_blank"
      - name: "Mealie"
        logo: "assets/tools/mealie.png"
        subtitle: "Powered by Mealie"
        url: "https://cookbook.kazjo.co"
        target: "_blank"
      - name: "Mealie"
        logo: "assets/tools/mealie.png"
        subtitle: "Powered by Mealie"
        url: "https://cookbook.kazjo.co"
        target: "_blank"
