version: "3.9"
services:
  octoprint:
    image: octoprint/octoprint:edge
    container_name: tolodbothir-octoprint
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      ENABLE_MJPG_STREAMER: "TRUE"
    ports:
      - ${TOLODBOTHIR_OCTOPRINT_PORT:-80}:80
    restart: unless-stopped
    volumes:
     - ${TOLODBOTHIR_OCTOPRINT_PATH:-./octoprint}:/octoprint
    deploy:
      placement:
        constraints: [node.labels.tolodbothir == true]
