version: "3.9"
services:
  octoprint:
    image: octoprint/octoprint:latest
    container_name: tolodbothir-octoprint
    devices:
      - /dev:/dev
    environment:
      ENABLE_MJPG_STREAMER: "TRUE"
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      NODE_ENV: development
    ports:
      - ${TOLODBOTHIR_OCTOPRINT_PORT}:80
    privileged: true
    restart: unless-stopped
    volumes:
     - ${TOLODBOTHIR_OCTOPRINT_PATH}:/octoprint
     - /dev:/dev
    deploy:
      replicas: 0
      placement:
        constraints: [node.labels.tolodbothir == true]
