version: "3.9"
services:
  octoprint:
    image: octoprint/octoprint:latest
    container_name: tolodbothir-octoprint
    devices:
     - /dev/ttyACM0:/dev/ttyACM0
    #  - /dev/video0:/dev/video0
    environment:
      ENABLE_MJPG_STREAMER: "FALSE"
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${TOLODBOTHIR_OCTOPRINT_PORT}:80
    restart: unless-stopped
    volumes:
     - octoprint-app:/octoprint
    deploy:
      placement:
        constraints: [node.labels.tolodbothir == true]

  config-editor:
    image: linuxserver/code-server
    container_name: tolodbothir-editor
    environment:
      PUID: ${PUID}
      GUID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${TOLODBOTHIR_VSCODE_PORT}:8443
    restart: unless-stopped
    volumes:
      - octoprint-app:/octoprint
    depends_on:
      - octoprint
    deploy:
      placement:
        constraints: [node.labels.tolodbothir == true]

volumes:
  octoprint-app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${ENEDOS_PATH}/tolodbothir/octoprint
