version: "3.9"
services:
  homer:
    image: b4bz/homer
    container_name: lochuil-homer
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      INIT_ASSETS: 1
    ports:
      - ${LOCHUIL_HOMER_PORT}:8080
    volumes:
      - ${LOCHUIL_HOMER_PATH}:/www/assets
    user: ${PUID}:${PGID}
    deploy:
      placement:
        constraints: [node.labels.lochuil == true]

  homer-admin:
    image: b4bz/homer
    container_name: lochuil-homer-admin
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      INIT_ASSETS: 1
    ports:
      - ${LOCHUIL_HOMER_PORT_ADMIN}:8080
    volumes:
      - ${LOCHUIL_HOMER_ADMIN_PATH}:/www/assets
    user: ${PUID}:${PGID}
    deploy:
      placement:
        constraints: [node.labels.lochuil == true]

  homer-editor:
    image: linuxserver/code-server
    container_name: lochuil-editor
    environment:
      PUID: ${PUID}
      GUID: ${PGID}
      TZ: ${TZ}
      PROXY_DOMAIN: ${LOCHUIL_VSCODE_URL}.${DOMAINS}
      DEFAULT_WORKSPACE: ${LOCHUIL_VSCODE_WORKSPACE}
    ports:
      - ${LOCHUIL_VSCODE_PORT}:8443
    restart: unless-stopped
    volumes:
       - ${LOCHUIL_HOMER_PATH}:/www/assets
    deploy:
      placement:
        constraints: [node.labels.lochuil == true]
    depends_on:
      - homer
      - homer-admin
