version: "3.9"
services:
  homer:
    image: b4bz/homer
    container_name: lochuil-homer
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      INIT_ASSETS: 1
    ports:
      - ${LOCHUIL_HOMER_PORT:-8080}:8080
    volumes:
      - ${LOCHUIL_HOMER_PATH:-./homer}:/www/assets
    user: ${PUID}:${PGID}
    deploy:
      placement:
        constraints: [node.labels.lochuil == true]

  homer-admin:
    image: b4bz/homer
    container_name: lochuil-homer-admin
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      INIT_ASSETS: 1
    ports:
      - ${LOCHUIL_HOMER_PORT_ADMIN:-8081}:8080
    volumes:
      - ${LOCHUIL_HOMER_PATH:-./homer}/admin:/www/assets
    user: ${PUID}:${PGID}
    deploy:
      placement:
        constraints: [node.labels.lochuil == true]

  homer-editor:
    image: linuxserver/code-server
    container_name: lochuil-editor
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PASSWORD: ${LOCHUIL_VSCODE_PASSWORD:-changeMe}
      PROXY_DOMAIN: ${LOCHUIL_VSCODE_URL:-vscode}.${DOMAINS:-changeMe.biz}
      DEFAULT_WORKSPACE: ${LOCHUIL_VSCODE_WORKSPACE:-./}
    ports:
      - ${LOCHUIL_VSCODE_PORT:-8443}:8443
    restart: unless-stopped
    volumes:
       - ${LOCHUIL_HOMER_PATH:-./homer}:/www/assets
    depends_on:
      - homer
    deploy:
      placement:
        constraints: [node.labels.lochuil == true]
