version: "3.9"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: aesordur-mealie
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      RECIPE_PUBLIC: "TRUE"
      RECIPE_SHOW_NUTRITION: "TRUE"
      RECIPE_SHOW_ASSETS: "TRUE"
      RECIPE_LANDSCAPE_VIEW: "TRUE"
      RECIPE_DISABLE_COMMENTS: "FALSE"
      RECIPE_DISABLE_AMOUNT: "FALSE"
      WORKERS_PER_CORE: 3
      DB_ENGINE: sqlite
      TOKEN_TIME: 4383
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: ${AESORDUR_MEALIE_URL:-https://mealie.example.com}
      ALLOW_SIGNUP: "FALSE"
    ports:
      - ${AESORDUR_MEALIE_PORT:-9000}:9000
    restart: always
    volumes:
      - ${AESORDUR_MEALIE_PATH:-./mealie}:/app/data
    deploy:
      labels:
        - homepage.description=Recipies and meal planning
        - homepage.href=${AESORDUR_MEALIE_URL:-https://mealie.example.com}
        - homepage.icon=mealie.svg
        - homepage.instance.admin.group=Aesordúr
        - homepage.instance.admin.name=Mealie
        - homepage.instance.public.group=Xanadu
        - homepage.instance.public.name=Cookbook
        - homepage.widget.type=mealie
        - homepage.widget.url=${RAEDORVUDH_IP:-http://mealie}:${AESORDUR_MEALIE_PORT:-9000}
        - homepage.widget.key=${API_MEALIE:-changeMe}
        - homepage.widget.fields=["recipes"]
      placement:
        constraints: [node.labels.aesordur == true]
