version: "3.9"
services:
  # Plex (https://docs.linuxserver.io/images/docker-plex)
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: nethiadil-plex
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      VERSION: docker
      PLEX_CLAIM: ${NETHIADIL_PLEX_CLAIM:-changeMe}
    network_mode: host
    ports:
      - ${NETHIADIL_PLEX_PORT:-32400}:32400/tcp
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_PLEX_PATH:-./plex}:/config
      - plex-media:/media
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints: [node.labels.nethiadil_plex == true]

  # Tautilli (https://docs.linuxserver.io/images/docker-tautulli)
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: nethiadil-plex-stats
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${NETHIADIL_TAUTULLI_PORT:-8181}:8181
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_TAUTULLI_PATH:-./tautulli}:/config
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  # Plex Meta Manager (https://docs.linuxserver.io/images/docker-plex-meta-manager)
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: nethiadil-metadata
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PMM_CONFIG: /config/config.yml
      PMM_TIME: ${NETHIADIL_PMM_UPDATE_TIME:-00:00}
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_PMM_PATH:-./plex-meta-manager}:/config:rw
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  # Beets (https://beets.io/)
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: nethiadil-beets
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${NETHIADIL_BEETS_PORT:-8337}:8337
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_BEETS_PATH:-./beets}:/config
      - thinmbahad-music-library:/music
      - thinmbahad-music:/downloads
    deploy:
      placement:
        constraints: [node.labels.nethiadil_music == true]

volumes:
  plex-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/media
  thinmbahad-music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/media/music/unprocessed
  thinmbahad-music-library:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/media/music/library
