version: "3.9"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: nethiadil-plex
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      VERSION: docker
      PLEX_CLAIM: ${NETHIADIL_PLEX_CLAIM}
    network_mode: host
    ports:
      - ${NETHIADIL_PLEX_PORT}:32400/tcp
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_PLEX_PATH}:/config
      - plex-media:/media
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: nethiadil-stats
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${NETHIADIL_TAUTULLI_PORT}:8181
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_TAUTULLI_PATH}:/config
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  overseerr:
    image: sctx/overseerr:latest
    container_name: nethiadil-overseerr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LOG_LEVEL: debug
    ports:
      - ${NETHIADIL_OVERSEERR_PORT}:5055
    volumes:
      - ${NETHIADIL_OVERSEERR_PATH}:/app/config
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: nethiadil-metadata
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      # PMM_CONFIG: /config/config.yml
      PMM_TIME: 03:00
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_PMM_PATH}:/config
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  ersatztv:
    image: jasongdove/ersatztv:develop-arm64
    container_name: nethiadil-ersatztv
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${NETHIADIL_ERSATZTV_PORT}:8409
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_ERSATZTV_PATH}:/root/.local/share/ersatztv
      - plex-media:/media/shared:ro
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

volumes:
  plex-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/media
