version: "3.9"
services:
  # Plex (https://docs.linuxserver.io/images/docker-plex)
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: nethiadil-plex
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      VERSION: docker
      PLEX_CLAIM: ${NETHIADIL_PLEX_CLAIM:-changeMe}
    network_mode: host
    ports:
      - ${NETHIADIL_PLEX_PORT:-32400}:32400/tcp
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_PLEX_PATH:-./plex}:/config
      - plex-media:/media
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        - homepage.instance.admin.group=Nethiadil
        - homepage.instance.admin.name=Plex Media Server
        - homepage.instance.public.group=Media
        - homepage.instance.public.name=Nickflix
        - homepage.description=Streaming media server
        - homepage.icon=plex.svg
        - homepage.href=${NETHIADIL_PLEX_URL:-http://localhost}
        - homepage.widget.type=plex
        - homepage.widget.url=${RAEDORVUDH_IP:-http://localhost}:${NETHIADIL_PLEX_PORT:-32400}
        - homepage.widget.key=${API_PLEX:-changeMe}
        - homepage.widget.fields=["movies", "tv", "albums"]
      placement:
        constraints: [node.labels.nethiadil_plex == true]

  # Tautilli (https://docs.linuxserver.io/images/docker-tautulli)
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: nethiadil-plex-stats
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${NETHIADIL_TAUTULLI_PORT:-8181}:8181
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_TAUTULLI_PATH:-./tautulli}:/config
    deploy:
      labels:
        - homepage.instance.admin.group=Nethiadil
        - homepage.instance.admin.name=Tautilli
        - homepage.instance.admin.description=Plex statistics
        - homepage.instance.admin.icon=tautulli.svg
        - homepage.instance.admin.href=${NETHIADIL_TAUTULLI_URL:-http://localhost}
        - homepage.instance.admin.widget.type=tautulli
        - homepage.instance.admin.widget.url=${RAEDORVUDH_IP:-http://localhost}:${NETHIADIL_TAUTULLI_PORT:-8181}
        - homepage.instance.admin.widget.key=${API_TAUTULLI:-changeMe}
        - homepage.instance.admin.widget.enableUser=true
        - homepage.instance.admin.widget.showEpisodeNumbers=true
        - homepage.instance.admin.widget.expandOneStreamToTwoRows=true
      placement:
        constraints: [node.labels.nethiadil == true]

  # Plex Meta Manager (https://docs.linuxserver.io/images/docker-plex-meta-manager)
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: nethiadil-plex-metadata
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PMM_CONFIG: /config/config.yml
      PMM_TIME: ${NETHIADIL_PMM_UPDATE_TIME:-00:00}
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_PMM_PATH:-./plex-meta-manager}/app:/config:rw
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]
  
  # Plex Meta Manager (https://docs.linuxserver.io/images/docker-plex-meta-manager)
  plex-meta-manager-editor:
    image: lscr.io/linuxserver/vscodium:latest
    container_name: nethiadil-plex-metadata-editor
    cap_add:
      - IPC_LOCK
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PASSWORD: ${NETHIADIL_PMM_PASSWORD:-changeMe}
      TITLE: Plex Meta Manager Editor
    ports:
      - ${NETHIADIL_PMM_PORT:-3000}:3000
      - ${NETHIADIL_PMM_PORT_SSL:-3001}:3001
    restart: unless-stopped
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ${NETHIADIL_PMM_PATH:-./plex-meta-manager}:/config
    deploy:
      labels:
          - homepage.instance.admin.group=Nethiadil
          - homepage.instance.admin.name=Plex Meta Manager
          - homepage.instance.admin.description=Metadata management for Plex Media Server
          - homepage.instance.admin.icon=/icons/plex-meta-manager.png
          - homepage.instance.admin.href=${NETHIADIL_PMM_URL:-http://localhost}
      placement:
        constraints: [node.labels.nethiadil == true]

  # Beets (https://beets.io/)
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: nethiadil-beets
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${NETHIADIL_BEETS_PORT:-8337}:8337
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_BEETS_PATH:-./beets}:/config
      - thinmbahad-music-library:/music
    deploy:
      labels:
          - homepage.instance.admin.group=Nethiadil
          - homepage.instance.admin.name=Beets
          - homepage.instance.admin.description=Music library management
          - homepage.instance.admin.icon=sh-beets
          - homepage.instance.admin.href=${NETHIADIL_BEETS_URL:-http://localhost}
      placement:
        constraints: [node.labels.nethiadil_music == true]

volumes:
  plex-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}
  thinmbahad-music-library:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/91.Audio/91.01.Music