version: "3.9"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: nethiadil-plex
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      VERSION: docker
      PLEX_CLAIM: ${NETHIADIL_PLEX_CLAIM:-changeMe}
    network_mode: host
    ports:
      - ${NETHIADIL_PLEX_PORT:-32400}:32400/tcp
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_PLEX_PATH:-./plex}:/config
      - plex-media:/media
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: nethiadil-stats
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${NETHIADIL_TAUTULLI_PORT:-8181}:8181
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_TAUTULLI_PATH:-./tautulli}:/config
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: nethiadil-metadata
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      PMM_CONFIG: ${NETHIADIL_PMM_PATH:-./plex-meta-manager}/${NETHIADIL_PMM_CONFIG_FILE:-.config.yaml}
      PMM_TIME: ${NETHIADIL_PMM_UPDATE_TIME:-00:00}
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_PMM_PATH:-./plex-meta-manager}:/config
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

  ersatztv:
    image: jasongdove/ersatztv:develop-arm64
    container_name: nethiadil-ersatztv
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${NETHIADIL_ERSATZTV_PORT:-8409}:8409
    restart: unless-stopped
    volumes:
      - ${NETHIADIL_ERSATZTV_PATH:-./ersatztv}:/root/.local/share/ersatztv
      - plex-media:/media/shared:ro
    deploy:
      placement:
        constraints: [node.labels.nethiadil == true]

volumes:
  plex-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/media