version: '3.9'
services:

  # Manyfold (https://manyfold.app)
  manyfold:
    image: lscr.io/linuxserver/manyfold:latest
    container_name: tolodbothur-manyfold
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      SECRET_KEY_BASE: ${TOLODBOTHUR_MANYFOLD_SECRET:-changeMe}
      DATABASE_URL: postgresql://${ROOT_USERNAME:-changeMe}:${ROOT_PASSWORD:-changeMe}@${RAEDORVUDH_IP:-127.0.0.1}:${POSTGRES_PORT:-5432}/${TOLODBOTHUR_MANYFOLD_DATABASE_NAME:-manyfold}
    networks:
      - gulhir
    ports:
      - ${TOLODBOTHUR_MANYFOLD_PORT:-3214}:3214
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${TOLODBOTHUR_MANYFOLD_PATH:-./manyfold}:/config
      - thinmbahad-models:/libraries
    deploy:
      placement:
        constraints: [node.labels.tolodbothur == true]

  # OctoPrint (https://octoprint.org)
  octoprint:
    image: octoprint/octoprint
    container_name: tolodbothur-octoprint
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    environment:
      ENABLE_MJPG_STREAMER: "true"
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
    ports:
      - ${TOLODBOTHUR_OCTOPRINT_PORT:-80}:80
    restart: unless-stopped
    volumes:
      - ${TOLODBOTHUR_OCTOPRINT_PATH:-./octoprint}:/octoprint
    deploy:
      placement:
        constraints: [node.labels.tolodbothur == true]

networks:
  gulhir:
    external: true

volumes:
  thinmbahad-models:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_IP},${NFS_OPTIONS}
        device: :${THINMBAHAD_PATH}/media/3d
