version: "3.9"
services:
  photoview:
    image: photoview/photoview:latest
    container_name: bavronalad-photoview
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Los_Angeles}
      MAPBOX_TOKEN: ${API_MAPBOX:-changeMe}
      PHOTOVIEW_DATABASE_DRIVER: postgres
      PHOTOVIEW_MEDIA_CACHE: ${BAVRONALAD_PHOTOVIEW_PATH:-./photoview}/cache
      PHOTOVIEW_POSTGRES_URL: postgresql://${ROOT_USERNAME:-changeMe}:${ROOT_PASSWORD:-changeMe}@${RAEDORVUDH_IP:-127.0.0.1}:${POSTGRES_PORT:-5432}/${BAVRONALAD_PHOTOVIEW_DATABASE_NAME:-photoview}
      PHOTOVIEW_SERVE_UI: 1
      PHOTOVIEW_UI_PATH: ${BAVRONALAD_PHOTOVIEW_PATH:-./photoview}/app
    networks:
      - gulhir
    ports:
      - ${BAVRONALAD_PHOTOVIEW_PORT:-80}:80
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - thinmbahad-photos-public:/photos:ro
    depends_on:
      - postgresql
    deploy:
      labels:
        - homepage.instance.admin.group=Bavronalad
        - homepage.instance.admin.name=Photoview
        - homepage.instance.admin.description=Photo management and sharing
        - homepage.instance.admin.icon=photoview.svg
      placement:
        constraints: [node.hostname == ] 
        
networks:
  gulhir:
    external: true

volumes:
  thinmbahad-photos-public:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},${NFS_OPTIONS}
      device: :${THINMBAHAD_PATH}/94.Photos/94.01.Public