version: "3.9"
services:
  server:
    image: gitea/gitea
    container_name: erebithron-gitea
    environment:
      TZ: ${TZ}
      USER_UID: ${PUID}
      USER_GID: ${PGID}
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: db:3306
      GITEA__database__NAME: ${EREBITHRON_GITEA_DB_DATABASE}
      GITEA__database__USER: ${EREBITHRON_GITEA_DB_USERNAME}
      GITEA__database__PASSWD: ${EREBITHRON_GITEA_DB_PASSWORD}
    ports:
      - ${EREBITHRON_GITEA_PORT}:3000
      - ${EREBITHRON_GITEA_PORT_SSL}:22
    restart: always
    volumes:
      - ${EREBITHRON_GITEA_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.labels.erebithron == true]

  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: erebithron-gitea-db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${EREBITHRON_GITEA_DB_USERNAME}
      MYSQL_PASSWORD: ${EREBITHRON_GITEA_DB_PASSWORD}
      MYSQL_DATABASE: ${EREBITHRON_GITEA_DB_DATABASE}
    restart: always
    volumes:
      - ${EREBITHRON_GITEA_PATH}/database:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.labels.database == true]

  hedgedoc:
    image: lscr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${EREBITHRON_HEDGEDOC_DB_USERNAME}
      DB_PASS: ${EREBITHRON_HEDGEDOC_DB_PASSWORD}
      DB_NAME: ${EREBITHRON_HEDGEDOC_DB_DATABASE}
    ports:
      - ${EREBITHRON_HEDGEDOC_PORT}:3000
    restart: unless-stopped
    volumes:
      - ${EREBITHRON_HEDGEDOC_PATH}:/config
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.labels.erebithron == true]

  snippet-box:
    image: pawelmalak/snippet-box:arm
    container_name: erebithron-snippet-box
    ports:
      - ${EREBITHRON_SNIPPET_PORT}:5000
    restart: unless-stopped
    volumes:
      - ${EREBITHRON_SNIPPET_PATH}:/app/data
    deploy:
      placement:
        constraints: [node.labels.erebithron == true]
